ログイン機能の実装
yanbaru-expert/team_project_51 pull request #29
Opened 2021-05-19 12:14 UTC by ryokobayashi0321

close #3

## 実装内容

- `gem : devise`を追加
- `マイグレーション`を実行/`パスワード再設定関連のカラム`をコメントアウト
- 全ページをログイン必須に変更(修正)
- 全てのページに`新規登録・ログイン・アカウント編集・ログアウトのリンク`を追加
- `homeコントローラ`を追加、`トップページからログイン画面に`リダイレク ト

## 参考資料（必要があれば）

- ログイン機能
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/219)
- Qiita
  - [Deviseの設定手順をまとめてみた。 その1　導入編](https://qiita.com/hakatatech/items/ea0d9236d89fa24a7a1c)

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-05-19 12:23 UTC, ryokobayashi0321 commented on app/controllers/home_controller.rb
> +end
トップページをログイン画面にリダイレクトできるようHomeコントローラを追加しました。

2021-05-19 12:23 UTC, ryokobayashi0321 commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
このコードでログイン画面にリダイレクトできると思いました。

2021-05-19 12:23 UTC, ryokobayashi0321 commented on app/views/home/index.html.erb
> +<p>Find me in app/views/home/index.html.erb</p>
Homeコントローラを追加した際にできたトップページ画面です。

2021-05-19 12:49 UTC, T-Tsujii commented on app/controllers/home_controller.rb
> +end
トップページはテキスト一覧ページですので不要です。

2021-05-19 12:49 UTC, T-Tsujii commented on app/views/home/index.html.erb
> +<p>Find me in app/views/home/index.html.erb</p>
こちらも削って下さい。

2021-05-19 12:51 UTC, T-Tsujii requested changes

2021-05-19 12:51 UTC, T-Tsujii commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
こちらはOKです！

2021-05-19 12:51 UTC, T-Tsujii commented on config/routes.rb
> +  root to: "home#index"
コンフリクトを解消し，`  root to: "home#index"`は削って下さい。

2021-05-20 05:21 UTC, ryokobayashi0321 reviewed
コンフリクトを解消しました。

2021-05-20 05:21 UTC, ryokobayashi0321 commented on app/assets/stylesheets/application.scss
> +
ここでエラーが出たので、削除したところ、動作が正常になりました。自分が記載したものではないのですが大丈夫なのでしょうか。

2021-05-20 06:06 UTC, T-Tsujii requested changes

2021-05-20 06:06 UTC, T-Tsujii commented on app/assets/stylesheets/application.scss
> +
この対応は間違っています。#8 で導入されたJSのライブラリを読み込む設定ですので，インストールされていないなら

```
yarn install --check-files
```

でデータ更新しましょう。

2021-05-20 06:41 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-20 07:10 UTC, merged