Railsテキスト教材詳細ページの実装
yanbaru-expert/team_project_51 pull request #41
Opened 2021-06-04 09:36 UTC by ryokobayashi0321

close #17

## 実装内容

- aタグの下線が入らないように設定
- 一覧ページから詳細ページに移動できるよう設定
- マークダウン形式を変換する `redcarpet`, シンタックスハイライトを適用する `rouge` をインストール
- markdown メソッドを`app/helpers/markdown_helper.rb` に作成
- `app/assets/stylesheets/rouge.scss.erb `を作成し，Rouge のシンタックスハイライト用のスタイルを追加
- 詳細ページを実装

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-06-04 09:40 UTC, ryokobayashi0321 commented on app/views/texts/show.html.erb
> +</div>
サンプルisueeに記載されていた`「タイトル(title)」と「内容(content)」を表示`の部分がよくわからなかったのですが、この記載でよろしいでしょうか。

2021-06-04 09:44 UTC, T-Tsujii requested changes

2021-06-04 09:44 UTC, T-Tsujii commented on app/views/texts/show.html.erb
> +</div>
直接書くことではなく，あくまで条件分岐のページでCSSが当たっていることをしっかり確認していただきたい，ということです。

他のページに影響の出る部分は削ってください。

2021-06-06 13:15 UTC, T-Tsujii requested changes

2021-06-06 13:15 UTC, T-Tsujii commented on app/views/texts/show.html.erb
> +</div>
タイトルはそのまま表示すべきでしょう。

```suggestion
<h1><% @text.title %></h1>
```

2021-06-06 13:15 UTC, T-Tsujii commented on app/views/texts/show.html.erb
> +  <%= markdown(@text.content).html_safe %>
`app/helpers/markdown_helper.rb` に入っていますよ。

```suggestion
  <%= markdown(@text.content) %>
```

2021-06-06 23:29 UTC, T-Tsujii approved these changes
LGTMです！

2021-06-07 01:04 UTC, merged